version: "3.3"

services:
  backend-api:
    build: ./backend/node
    restart: always
    # working directory in container to place files
    working_dir: /usr/src/app
    # #### startup command for cloud #### UNCOMMENT IF USING CLOU
    command: bash -c "yarn run dev"
    # map code volumes from local to inside working directory, changes made locally will update into the container
    volumes:
      - ./backend/node:/usr/src/app
    # specify dependency on mysql db
    depends_on:
      - backend-db
    # ports to map, YOU CANNOT RUN ANYTHING ELSE ON PORT 8000
    ports:
      - 8000:8000
    # shared network
    networks:
      - api

  frontend-app:
    stdin_open: true
    build: ./frontend
    restart: always
    # working directory in container to place files
    working_dir: /usr/src/app
    # startup command 
    command: bash -c "yarn start"
    # map code volumes from local to inside working directory, changes made locally will update into the container
    volumes:
      - ./frontend:/usr/src/app
    # specify dependency on mysql db
    depends_on:
      - backend-api
    # ports to map, YOU CANNOT RUN ANYTHING ELSE ON PORT 3000
    ports:
      - 3000:3000
    # shared network
    networks:
      - api

# specify networks
networks:
  api:
